development
prototype2010/request-trap pull request #1
Opened 2020-01-30 14:36 UTC by prototype2010

2020-02-03 19:44 UTC, GerashenkoVladimir requested changes

2020-02-03 19:44 UTC, GerashenkoVladimir commented on .env.example
> +DB_NAME='your_db_name'
нет возможности изменить хост:порт монги

2020-02-03 19:44 UTC, GerashenkoVladimir commented on app/server.ts
>  import express from 'express';
/server.ts обычно в корне находится

2020-02-03 19:44 UTC, GerashenkoVladimir commented on app/controllers/HomePageController.ts
> +  get(): void {
рендеришь индекс а екшен называешь get
называя следуя соглашениям будет сразу понятно каким методом должен прийти запрос и что там творится

2020-02-03 19:44 UTC, GerashenkoVladimir commented on app/controllers/RequestsController.ts
> +  async get(): Promise<void> {
тут по сути вывод индексной ручки всех запросов

2020-02-03 19:44 UTC, GerashenkoVladimir commented on .gitignore
> +build
.env забыл)

2020-02-03 19:44 UTC, GerashenkoVladimir commented on .gitignore
> +build
.env*
!.env.example
так еще можно

2020-02-03 19:44 UTC, GerashenkoVladimir commented on app/controllers/HomePageController.ts
> +    super(req, res, notifier);
дублируешь в каждом контроллере

2020-02-03 19:44 UTC, GerashenkoVladimir commented on app/controllers/utils/Controller.ts
> +  protected async initTrap(): Promise<any> {
это не метод базового контроллера

2020-02-03 19:44 UTC, GerashenkoVladimir commented on app/controllers/TrapController.ts
> +    const trap = await super.initTrap();
а почему через super а не через this?

2020-02-03 19:44 UTC, GerashenkoVladimir commented on app/database/entities/Request/RequestFactory.ts
> +export class RequestFactory {
я бы не сказал что это фабрика реквестов
тут по факту лишь екстрактятся из хттп реквеста данные и билдятся в нужный объект
+ не рекомендуется называть именем паттерна то что не является его реализацией

2020-02-03 19:44 UTC, GerashenkoVladimir commented on app/database/entities/Request/RequestFactory.ts
> +  static create(req: express.Request, trapId: string): HTTPRequestInfo & RequestFactoryInfo {
я бы наверное это оставил в самом контроллере так как тут логика завязана сильно на объекте екпресс реквеста и без него не особо где то нужна

2020-02-03 19:44 UTC, GerashenkoVladimir commented on app/database/entities/Request/RequestExtractorConfig.ts
> +export const RequestBulkExtractor = new BulkPropertyExtractor<HTTPRequestInfo>([
это уже оверхед

2020-02-03 19:44 UTC, GerashenkoVladimir commented on app/controllers/TrapController.ts
> +    const requestInfo = RequestFactory.create(this.req, trap._id);
requestInfoParams?

2020-02-03 19:44 UTC, GerashenkoVladimir commented on app/controllers/TrapController.ts
> +    const mongooseModel = new HttpRequestInfo(requestInfo);
const requestInfo = new HttpRequestInfo(requestInfo);
а тут уже более правильно

2020-02-03 19:44 UTC, GerashenkoVladimir commented on app/controllers/TrapController.ts
> +    const savedRequest = await mongooseModel.save();
в чем разница между ними mongooseModel и savedRequest?

2020-02-03 19:44 UTC, GerashenkoVladimir commented on app/database/entities/Trap/TrapModel.ts
> +export const Trap = mongoose.model('Trap', TrapSchema);
почему не в одном файле со схемой?

2020-02-03 19:44 UTC, GerashenkoVladimir commented on app/database/entities/Request/HttpRequestInfoModel.ts
> +  trapId: string;
с реоейшенами не совсем мне понятно

2020-02-04 16:05 UTC, prototype2010 commented on .env.example
> +DB_NAME='your_db_name'
+

2020-02-04 16:06 UTC, prototype2010 commented on .gitignore
> +build
+

2020-02-04 16:14 UTC, prototype2010 commented on app/controllers/HomePageController.ts
> +    super(req, res, notifier);
+

2020-02-04 16:14 UTC, prototype2010 commented on app/controllers/HomePageController.ts
> +  get(): void {
+

2020-02-04 16:15 UTC, prototype2010 commented on app/controllers/TrapController.ts
> +    const trap = await super.initTrap();
+

2020-02-04 16:19 UTC, prototype2010 commented on app/controllers/TrapController.ts
> +    const requestInfo = RequestFactory.create(this.req, trap._id);
+

2020-02-04 16:19 UTC, prototype2010 commented on app/controllers/TrapController.ts
> +    const mongooseModel = new HttpRequestInfo(requestInfo);
+

2020-02-04 16:21 UTC, prototype2010 commented on app/controllers/TrapController.ts
> +    const savedRequest = await mongooseModel.save();
+

2020-02-04 16:21 UTC, prototype2010 commented on app/controllers/utils/Controller.ts
> +  protected async initTrap(): Promise<any> {
+

2020-02-05 08:25 UTC, prototype2010 commented on app/database/entities/Request/RequestExtractorConfig.ts
> +export const RequestBulkExtractor = new BulkPropertyExtractor<HTTPRequestInfo>([
+

2020-02-05 08:35 UTC, prototype2010 commented on app/database/entities/Request/RequestFactory.ts
> +export class RequestFactory {
+

2020-02-05 08:35 UTC, prototype2010 commented on app/database/entities/Request/RequestFactory.ts
> +  static create(req: express.Request, trapId: string): HTTPRequestInfo & RequestFactoryInfo {
+

2020-02-05 08:36 UTC, prototype2010 commented on app/database/entities/Trap/TrapModel.ts
> +export const Trap = mongoose.model('Trap', TrapSchema);
+

2020-02-05 14:29 UTC, merged